// app.js - example API project generated by Kaelum (API template)
const kaelum = require("kaelum");

const app = kaelum();

// enable basic safety + logs via setConfig
app.setConfig({
  cors: true,
  helmet: true,
  logs: true, // uses morgan internally
  bodyParser: true,
});

// mount routes
const routes = require("./routes");
routes(app);

// health check
app.healthCheck("/health");

// use Kaelum generic error handler (JSON responses)
app.useErrorHandler({ exposeStack: false });

// start server
const PORT = process.env.PORT || 4000;
app.start(PORT);